#!/usr/bin/env python3
import argparse, os

def get_path(*args):
    return os.path.expanduser(os.path.join(*args))

def search_directory(directory, text):
    for fd in os.listdir(path=get_path(directory)): 
        fullpath = get_path(directory, fd)
        # print(f"directory: {directory}")
        # print(f"fullpath: {fullpath}")
        # print(f"fd: {fd}")
        if os.path.isfile(fullpath):
            file=open(fullpath.format(), 'r')
            content = file.read()
            if content.find(text) != -1:
                print(f"File {fullpath} has content \"{text}\".")
        else: 
            search_directory(fullpath, text)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Search text in text files.')
    parser.add_argument('directory', help='Directory to scan.')
    parser.add_argument('text', help='Text to search.')
    args = parser.parse_args()
    search_directory(args.directory, args.text)
